#!/bin/bash
#
# (c) 2012 YeaSoft Int'l - Leo Moll
#
# uic chroot hook:      chroot_post_installation
# called by:            uic_create, uic_upgrade
#
# This hook will be called by uic_create in the chrooted installation
# environment in $TARGET after making all software installation and
# configuration steps. Since this hook runs in chroot, none of the
# internal UIC variables are available.

# make sure all installed services that may be autostarted are stopped
/etc/init.d/portmap stop > /dev/null 2> /dev/null
/etc/init.d/nfs-common stop > /dev/null 2> /dev/null
/etc/init.d/cron stop > /dev/null 2> /dev/null
# reset the error code to no error
ls > /dev/null
