#!/bin/sh
#
# (c) 2012 YeaSoft Int'l - Leo Moll
#
# This initramfs hook prepares the initial ramdisk for the
# yeasoft extended boot system

PREREQS=""

# Output pre-requisites
prereqs()
{
       echo "$PREREQS"
}

case "$1" in
    prereqs)
       prereqs
       exit 0
       ;;
esac

. /usr/share/initramfs-tools/hook-functions

mkdir -p ${DESTDIR}/lib/udev
copy_exec /lib/udev/cdrom_id /lib/udev
copy_exec /lib/udev/vol_id /lib/udev
copy_exec /lib/udev/path_id /lib/udev

# squashfs
manual_add_modules squashfs
manual_add_modules loop

# random file system modules
manual_add_modules vfat
manual_add_modules ext3
# needed for vfat. :-/
manual_add_modules nls_cp437
manual_add_modules nls_utf8
manual_add_modules nls_iso8859-1

# cdrom modules
manual_add_modules sr_mod
manual_add_modules ide-cd
manual_add_modules sbp2
manual_add_modules ohci1394

# auto_add_modules net
