#!/bin/bash
#
# (c) 2012 YeaSoft Int'l - Leo Moll
#
# uic hook:	pre_build_initrd
# called by:	uic_build
#
# This hook will be called by uic_build before performing an initial ramdisk
# build procedure in the installation environment in $TARGET

if [ "$UIC_BUILDNAME" = "netpoldo-integrated" ]; then
	# test if the squash filesystem is available
	if [ -f "${TARGET}/output/netpoldo.squashfs" ]; then
		cp "${TARGET}/output/netpoldo.squashfs"	"${TARGET}/chroot"
	else
		show_error "Missing netpoldo.squashfs"
		exit 2
	fi
fi
