#!/bin/bash
#
# (c) 2012 YeaSoft Int'l - Leo Moll
#
# uic hook:     post_build_initrd
# called by:	uic_build
#
# This hook will be called by uic_build after performing an initial ramdisk
# build procedure in the installation environment in $TARGET

if [ "$UIC_BUILDNAME" = "netpoldo-integrated" ]; then
	rm -f "${TARGET}/chroot/netpoldo.squashfs"
fi
