#!/bin/bash
#
# (c) 2012-2014 YeaSoft Int'l - Leo Moll
#
# uic chroot hook:      chroot_post_installation
# called by:            uic_create, uic_upgrade
#
# This hook will be called by uic_create in the chrooted installation
# environment in $TARGET after making all software installation and
# configuration steps. Since this hook runs in chroot, none of the
# internal UIC variables are available.

# INSTALL EXTLINUX MANUALLY
# we need the extlinux binary but unfortunately it is not included
# any more in syslinux. The package extlinux does not only contain
# the binary but also a collection of scripts AND hooks for installing
# and updating the boot manager every time the kernel is updated or
# changed.

pushd /root
apt-get download extlinux
mkdir -p extlinux
dpkg -x extlinux*.deb extlinux
mv extlinux/usr/bin/extlinux /usr/bin
rm -rf extlinux*
popd

# make sure we do not exit with no error
[ 1 = 1 ]
