#!/bin/sh
#
# (c) 2012 YeaSoft Int'l - Leo Moll
#
# This initramfs script implements support for basic keyboard
# layout selection from the kernel comandline.

PREREQ=""
prereqs()
{
        echo "$PREREQ"
}

# get pre-requisites
case $1 in
prereqs)
        prereqs
        exit 0
        ;;
esac

. ./scripts/functions

KEYBOARD=
KMAP=
KLAY=
KVAR=
KOPT=

log_begin_msg "Parsing overlay specific parameters..."
# Parse command line options
for x in $(cat /proc/cmdline); do
        case $x in
	keyboard=*)
		KEYBOARD=${x#keyboard=}
		case $KEYBOARD in
		de)	KMAP=de.kmap.gz; KLAY="de"; KVAR="deadgraveacute"; KOPT="";;
		it)	KMAP=it.kmap.gz; KLAY="it"; KVAR=""; KOPT="";;
		fr)	KMAP=fr.kmap.gz; KLAY="fr"; KVAR=""; KOPT="";;
		es)	KMAP=es.kmap.gz; KLAY="es"; KVAR=""; KOPT="";;
		*)	;;
		esac
		;;
	esac
done
log_end_msg

if [ "$KMAP" != "" ]; then
	[ "$quiet" != "y" ] && log_begin_msg "Setting keyboard mapping to ${KEYBOARD}..."
	if [ -e ${rootmnt}/etc/console-setup/${KMAP} ]; then
		cp ${rootmnt}/etc/console-setup/${KMAP} ${rootmnt}/etc/console-setup/boottime.kmap.gz
	fi
	if [ -e ${rootmnt}/etc/default/keyboard ]; then
		cat ${rootmnt}/etc/default/keyboard | sed -e "s/XKBLAYOUT=\"us\"/XKBLAYOUT=\"${KLAY}\"/g" | sed -e "s/XKBVARIANT=\"\"/XKBVARIANT=\"${KVAR}\"/g" | sed -e "s/XKBOPTIONS=\"\"/XKBOPTIONS=\"${KOPT}\"/g" > /keyboard
		mv /keyboard ${rootmnt}/etc/default/keyboard
	elif [ -e ${rootmnt}/etc/default/console-setup ]; then
		cat ${rootmnt}/etc/default/console-setup | sed -e "s/XKBLAYOUT=\"us\"/XKBLAYOUT=\"${KLAY}\"/g" | sed -e "s/XKBVARIANT=\"\"/XKBVARIANT=\"${KVAR}\"/g" | sed -e "s/XKBOPTIONS=\"\"/XKBOPTIONS=\"${KOPT}\"/g" > /keyboard
		mv /keyboard ${rootmnt}/etc/default/console-setup
	fi
	[ "$quiet" != "y" ] && log_end_msg
fi

unset KEYBOARD
unset KMAP
unset KLAY
unset KVAR
unset KOPT
