#!/bin/sh
#
# (c) 2015 YeaSoft Int'l - Leo Moll
#
# This script is part of the YeaSoft initramfs live system
# configuration
#
# This initramfs script repairs the value of the init variable
# previously destroyed by validate_init because validate_init
# was not able to find /sbin/init before the squash file system
# was mounted...
#
# Version: 20150912

PREREQ=""
prereqs()
{
        echo "$PREREQ"
}

# get pre-requisites
case $1 in
prereqs)
        prereqs
        exit 0
        ;;
esac

# prevent multiple execution
if [ -f /tmp/yealiveboot.init-bottom ]; then
	return 0
else
	touch /tmp/yealiveboot.init-bottom
fi

if [ "${YEABOOT_VENDOR}" = "Debian" -a "${YEABOOT_GENERATION}" = "2014" ]; then
	log_begin_msg "Repairing init parameter..."
	echo "init=\"/sbin/init\"" >> /conf/param.conf
	log_end_mdg
fi
