#!/bin/sh
#
# (c) 2012-2014 YeaSoft Int'l - Leo Moll
#
# This initramfs script implements support for basic keyboard
# layout selection from the kernel comandline.

PREREQ=""
prereqs()
{
        echo "$PREREQ"
}

# get pre-requisites
case $1 in
prereqs)
        prereqs
        exit 0
        ;;
esac

. ./scripts/functions

KEYBOARD=
KMAP=
KLAY=
KVAR=
KOPT=

log_begin_msg "Parsing overlay specific parameters..."
# Parse command line options
for x in $(cat /proc/cmdline); do
        case $x in
	keyboard=*)
		KEYBOARD=${x#keyboard=}
		case ${KEYBOARD} in
		de)	KMAP="de.kmap.gz"; KLAY="de"; KVAR="deadgraveacute"; KOPT="";;
		ru)	KMAP="ru.kmap.gz"; KLAY="us,ru"; KVAR=""; KOPT="";;
		??)	KMAP="${KEYBOARD}.kmap.gz"; KLAY="${KEYBOARD}"; KVAR=""; KOPT="";;
		*)	;;
		esac
		;;
	esac
done
log_end_msg

if [ "$KMAP" != "" ]; then
	[ "$quiet" != "y" ] && log_begin_msg "Setting keyboard mapping to ${KEYBOARD}..."
	if [ -e ${rootmnt}/etc/console-setup/${KMAP} ]; then
		cp -a ${rootmnt}/etc/console-setup/${KMAP} ${rootmnt}/etc/console-setup/cached.kmap.gz
		cp -a ${rootmnt}/etc/console-setup/${KMAP} ${rootmnt}/etc/console-setup/boottime.kmap.gz
		cp -a ${rootmnt}/etc/console-setup/${KMAP} ${rootmnt}/etc/console-setup/defkeymap.kmap.gz
	fi
	if [ -e ${rootmnt}/etc/default/keyboard ]; then
		sed -i	-e "s/XKBLAYOUT=\"us\"/XKBLAYOUT=\"${KLAY}\"/g" \
			-e "s/XKBVARIANT=\"\"/XKBVARIANT=\"${KVAR}\"/g" \
			-e "s/XKBOPTIONS=\"\"/XKBOPTIONS=\"${KOPT}\"/g" \
			${rootmnt}/etc/default/keyboard
	fi
	if [ -e ${rootmnt}/etc/default/console-setup ]; then
		sed -i	-e "s/XKBLAYOUT=\"us\"/XKBLAYOUT=\"${KLAY}\"/g" \
			-e "s/XKBVARIANT=\"\"/XKBVARIANT=\"${KVAR}\"/g" \
			-e "s/XKBOPTIONS=\"\"/XKBOPTIONS=\"${KOPT}\"/g" \
			${rootmnt}/etc/default/console-setup
	fi
	[ "$quiet" != "y" ] && log_end_msg
fi

unset KEYBOARD
unset KMAP
unset KLAY
unset KVAR
unset KOPT
