#!/bin/sh
#
# (c) 2012 YeaSoft Int'l - Leo Moll
#
# This initramfs script implements support for basic keyboard
# layout selection from the kernel comandline.

PREREQ=""
prereqs()
{
        echo "$PREREQ"
}

# get pre-requisites
case $1 in
prereqs)
        prereqs
        exit 0
        ;;
esac

. ./scripts/functions

KEYBOARD=
KMAP=

log_begin_msg "Parsing overlay specific parameters..."
# Parse command line options
for x in $(cat /proc/cmdline); do
        case $x in
	keyboard=*)
		KEYBOARD=${x#keyboard=}
		case $KEYBOARD in
		us)	KMAP=us.kmap.gz;;
		de)	KMAP=de.kmap.gz;;
		it)	KMAP=it.kmap.gz;;
		fr)	KMAP=fr.kmap.gz;;
		es)	KMAP=es.kmap.gz;;
		*)	;;
		esac
		;;
	esac
done
log_end_msg

if [ "$KMAP" != "" ]; then
	[ "$quiet" != "y" ] && log_begin_msg "Setting keyboard mapping to ${KEYBOARD}..."
	cp ${rootmnt}/etc/console-setup/${KMAP} ${rootmnt}/etc/console-setup/boottime.kmap.gz
	[ "$quiet" != "y" ] && log_end_msg
fi
