#!/bin/sh
#
# (c) 2012-2015 YeaSoft Int'l - Leo Moll
#
# This script is part of the YeaSoft initramfs live system
# configuration
#
# This specific script provides some global variables and
# specifies on which platform it will be running
#
# Version: 20150913

# Specify the distribution vendor
# Supported Choices: Debian, Ubuntu
export YEABOOT_VENDOR=Debian

# Specify the operating system generation
# Supported Choices: 2010,2012,2014
export YEABOOT_GENERATION=2012

# make sure this global variables are really accessible
# from every part of the script
export LOOP=${LOOP}
export LOOPFLAGS=${LOOPFLAGS}
export LOOPFSTYPE=${LOOPFSTYPE}
export init=${init}
